#!/bin/bash

python train.py convnetquakeingv lendb1k5_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lomax-lendb1k5_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb9k_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lomax-lendb9k_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb1k5_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-stead-lendb1k5_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb9k_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-stead-lendb9k_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb1k5_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-speech8khz-lendb1k5_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb9k_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-speech8khz-lendb9k_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb1k5_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-emg-lendb1k5_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb9k_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-emg-lendb9k_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb1k5_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-sp500-lendb1k5_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lendb9k_2 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-sp500-lendb9k_2-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
