#!/bin/bash

python train.py convnetquakeingv lomax1k5_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lendb-lomax1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax9k_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lendb-lomax9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax1k5_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-stead-lomax1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax9k_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-stead-lomax9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax1k5_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-speech8khz-lomax1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax9k_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-speech8khz-lomax9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax1k5_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-emg-lomax1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax9k_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-emg-lomax9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax1k5_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-sp500-lomax1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv lomax9k_1 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-sp500-lomax9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
