#!/bin/bash

python train.py convnetquakeingv sp5001k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lomax-sp5001k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5009k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lomax-sp5009k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5001k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lendb-sp5001k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5009k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-lendb-sp5009k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5001k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-stead-sp5001k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5009k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-stead-sp5009k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5001k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-speech8khz-sp5001k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5009k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-speech8khz-sp5009k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5001k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-emg-sp5001k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py convnetquakeingv sp5009k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name convnetquakeingv-emg-sp5009k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights convnetquakeingv-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
