#!/bin/bash

python train.py mlstm_fcn stead1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lomax-stead1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lomax/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lomax-stead9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lomax/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lendb-stead1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lendb/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lendb-stead9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lendb/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-speech8khz-stead1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-speech8khz/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-speech8khz-stead9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-speech8khz/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-emg-stead1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-emg/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-emg-stead9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-emg/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-sp500-stead1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-sp500/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn stead9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-sp500-stead9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-sp500/ --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
