#!/bin/bash

python train.py mlstm_fcn sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lomax-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lomax-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lendb-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lendb-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-stead-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-stead-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-speech8khz-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-speech8khz-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-emg-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-emg-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
