#!/bin/bash

python train.py magnet emg1k5_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-emg1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg9k_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-emg9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg1k5_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lendb-emg1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg9k_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lendb-emg9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg1k5_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-emg1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg9k_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-emg9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg1k5_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-speech8khz-emg1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg9k_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-speech8khz-emg9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg1k5_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-sp500-emg1k5_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet emg9k_1 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-sp500-emg9k_1-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
