#!/bin/bash

python train.py magnet sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lendb-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lendb-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-speech8khz-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-speech8khz-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5001k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-emg-sp5001k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet sp5009k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-emg-sp5009k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
