#!/bin/bash

python train.py magnet lendb1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-lendb1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-lendb9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-lendb1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-lendb9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-speech8khz-lendb1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-speech8khz-lendb9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-emg-lendb1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-emg-lendb9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-sp500-lendb1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet lendb9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-sp500-lendb9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
