#!/bin/bash

python train.py magnet speech8khz1k5_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-speech8khz1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz9k_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lomax-speech8khz9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz1k5_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lendb-speech8khz1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz9k_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-lendb-speech8khz9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz1k5_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-speech8khz1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz9k_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-stead-speech8khz9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz1k5_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-emg-speech8khz1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz9k_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-emg-speech8khz9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz1k5_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-sp500-speech8khz1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py magnet speech8khz9k_0 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name magnet-sp500-speech8khz9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights magnet-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
