#!/bin/bash

python train.py mlstm_fcn lomax1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lendb-lomax1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-lendb-lomax9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-stead-lomax1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-stead-lomax9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-speech8khz-lomax1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-speech8khz-lomax9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-emg-lomax1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-emg-lomax9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax1k5_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-sp500-lomax1k5_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py mlstm_fcn lomax9k_5 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name mlstm_fcn-sp500-lomax9k_5-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights mlstm_fcn-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
