#!/bin/bash

python train.py tcn sp5001k5_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lomax-sp5001k5_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5009k_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lomax-sp5009k_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5001k5_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lendb-sp5001k5_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5009k_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lendb-sp5009k_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5001k5_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-stead-sp5001k5_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5009k_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-stead-sp5009k_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5001k5_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-speech8khz-sp5001k5_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5009k_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-speech8khz-sp5009k_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5001k5_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-emg-sp5001k5_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn sp5009k_4 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-emg-sp5009k_4-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
