#!/bin/bash

python train.py tcn speech8khz1k5_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lomax-speech8khz1k5_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz9k_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lomax-speech8khz9k_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz1k5_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lendb-speech8khz1k5_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz9k_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lendb-speech8khz9k_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lendb/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz1k5_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-stead-speech8khz1k5_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz9k_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-stead-speech8khz9k_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz1k5_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-emg-speech8khz1k5_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz9k_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-emg-speech8khz9k_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz1k5_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-sp500-speech8khz1k5_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn speech8khz9k_6 classification --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-sp500-speech8khz9k_6-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
