#!/bin/bash

python train.py tcn lendb1k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lomax-lendb1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb9k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-lomax-lendb9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-lomax/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb1k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-stead-lendb1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb9k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-stead-lendb9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-stead/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb1k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-speech8khz-lendb1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb9k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-speech8khz-lendb9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-speech8khz/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb1k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-emg-lendb1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb9k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-emg-lendb9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-emg/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb1k5_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-sp500-lendb1k5_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
python train.py tcn lendb9k_0 regression --epochs 250 --lr 0.001 --lr-reducer --early-stopping --name tcn-sp500-lendb9k_0-$LR_MULTIPLIER --lr-multiplier $LR_MULTIPLIER --weights tcn-sp500/ --use-max-stream --cudnn-lstm --save-best --save-all --log-to-file --verbose 2
